import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-900 text-gray-100`}
      >
        <HeaderBar />
        <div className="flex">
          <AsideBar />
          <main className="w-3/4 12 bg-gray-200/5 text-gray-200 rounded-xl ml-4">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}

function HeaderBar() {
  return (
    <header className="h-16 z-10000 sticky top-0 w-full text-white bg-inherit">
      <nav className="w-full flex flex-row justify-between px-6 items-center">
        <div className="p-2">
          <Image src="/vercel.svg" alt="Logo" width={40} height={40} />
        </div>
        <ul className="inline-flex justify-center items-center h-full">
          <li className="p-2">Home</li>
          <li className="p-2">About</li>
          <li className="p-2">Contact</li>
          <div className="w-12"></div>
        </ul>
        <Link
          href="/login"
          className="bg-blue-500 text-white px-4 py-2 rounded-md"
        >
          Sign In
        </Link>
      </nav>
    </header>
  );
}

function AsideBar() {
  return (
    <aside className="w-1/4 h-[calc(100vh-4rem)] sticky top-16 bg-gray-200/5 text-gray-200 rounded-xl">
      <ul className="flex flex-col">
        <li className="p-2">
          <Link href="/">Home</Link>
        </li>
        <li className="p-2">
          <Link href="/about">About</Link>
        </li>
        <li className="p-2">
          <Link href="/contact">Contact</Link>
        </li>
      </ul>
    </aside>
  );
}
